// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificationApp.proto

package com.starnft.star.api.notice.req;

public interface MessageSendRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.starnft.star.api.notice.req.MessageSendRequest)
        com.google.protobuf.MessageOrBuilder {
}
