// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificationApp.proto

package com.starnft.star.api.notice;

public final class NotificationApp {
    private NotificationApp() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_starnft_star_api_notice_MessageSendRequest_descriptor;
    public static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_starnft_star_api_notice_MessageSendRequest_fieldAccessorTable;
    public static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_starnft_star_api_notice_MessageSendResponse_descriptor;
    public static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_starnft_star_api_notice_MessageSendResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\025NotificationApp.proto\022\033com.starnft.sta" +
                        "r.api.notice\"\024\n\022MessageSendRequest\"\025\n\023Me" +
                        "ssageSendResponse2\215\001\n\024NotificationDelive" +
                        "ry\022u\n\016sendStandalone\022/.com.starnft.star." +
                        "api.notice.MessageSendRequest\0320.com.star" +
                        "nft.star.api.notice.MessageSendResponse\"" +
                        "\000B\002P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_com_starnft_star_api_notice_MessageSendRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_starnft_star_api_notice_MessageSendRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_starnft_star_api_notice_MessageSendRequest_descriptor,
                new java.lang.String[]{});
        internal_static_com_starnft_star_api_notice_MessageSendResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_starnft_star_api_notice_MessageSendResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_starnft_star_api_notice_MessageSendResponse_descriptor,
                new java.lang.String[]{});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
