// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificationApp.proto

package com.starnft.star.api.notice.res;

public interface MessageSendResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.starnft.star.api.notice.res.MessageSendResponse)
        com.google.protobuf.MessageOrBuilder {
}
