spring:
  application:
    name: star-manager
  datasource:
    username: root
    password: wqd1234.
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://sh-cynosdbmysql-grp-ibkpxd68.sql.tencentcdb.com:23543/star?serverTimezone=GMT%2B8&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-wait: 60000
  redis:
    host: 124.221.181.84
    database: 0
    port: 16379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
    password: wqd123456.

server:
  port: 8088

logging:
  level:
    com.starnft.star: debug

mybatis:
  config-location:  classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mappers/**/*Mapper.xml

wallet:
  file:
    path: generator/english
swagger:
  packages: com.starnft.star.management.controller