{"body":
{"subject":"充值",
"payMode":"sand_upsdk",
"limitPay":"1",
"frontUrl":"${payment.frontUrl}",
"body":"充值",
"totalAmount":"${helper.yuanToFen(payment.totalMoney)}",
"txnTimeOut":"${outLineTime}",
"clientIp":"${payment.clientIp}",
"notifyUrl":"${conf.notify}",
"orderCode":"${payment.orderSn}"},
"head":
{"method":"sandpay.trade.pay",
"productId":"00000030",
"mid":"${conf.mid}",
"channelType":"08","reqTime":"${currentTime}",
"version":"1.0",
"accessType":"1"}
}