https://faspay-oss.sandpay.com.cn/pay/h5/cloud?
version=10&
mer_no=${param1.mid!''}
&mer_key=${helper.urlEscape(param1.merKey!'')}
&mer_order_no=${param3!''}
&create_time=${createTime!''}
&expire_time=${endTime!''}
&order_amt=0.01
&notify_url=${helper.urlEscape(param1.notify!'')}
&return_url=${helper.urlEscape(param2.returnUri!'')}
&create_ip=127_0_0_1
&goods_name=${helper.urlEscape('开户')}
&store_id=000000&product_code=00000001
&clear_cycle=3
&pay_extra=${helper.urlEscape('{"nickName":"${param2.realName}","userId":"${param2.userId}"}')}
&meta_option=${helper.urlEscape('[{"s":"Android","n":"CircleMeta","id":"cn.CircleMeta.app","sc":"/index"},{"s":"IOS","n":"CircleMeta","id":"cn.CircleMeta.app","sc":"/index"}]')}
&accsplit_flag=NO
&jump_scheme=
&sign_type=MD5
&sign=${param4!''}